### ISSUE TITLE
Add support for relay list from kind 3

### ISSUE THREAD

**Issue by AsaiToshiya** [dluvian/Nozzle#27]
Many clients also use the relay list from `kind: 3`.

**Comment by dluvian** [comment]
I don't like to overload events. It would make it harder for relay operators to moderate their relays and clients would have to process more data. 

Kind 3 is meant for contact lists and its content field [should be ignored](https://github.com/nostr-protocol/nips/blob/master/02.md). There is [nip65/kind10002](https://github.com/nostr-protocol/nips/blob/master/65.md) for sharing relay lists which Nozzle already uses.

**Comment by AsaiToshiya** [comment]
I agree, but I think it would be better not to overwrite the `content` with empty.

**Comment by dluvian** [comment]
Nozzle is ignoring the content field and therefore has to overwrite it with empty once you follow/unfollow someone. Ignoring the content is standard behavior (see nip02). It would be better for the other clients you are referring to to implement nip65.

**Comment by AsaiToshiya** [comment]
I understand your thought, I'm going to close this issue.
