### ISSUE TITLE
nip-42

### ISSUE THREAD

**Issue by Yonle** [dluvian/Nozzle#45]
Probably implement NIP-42?
Even this client does not utilize private messages, This could be useful for some strict relays that requires user to have NIP-42 authenticated to read / post stuffs.

**Comment by dluvian** [comment]
It's on my list.

**Comment by dluvian** [comment]
I forgot about this issue. It has already been implemented in [v0.15.3](https://github.com/dluvian/Nozzle/releases/tag/v0.15.3), current release is [v0.16.0](https://github.com/dluvian/Nozzle/releases/tag/v0.16.0).
