### ISSUE TITLE
Change color of topbar into white?

### ISSUE THREAD

**Issue by Yonle** [dluvian/Nozzle#46]
If we could do pure black topbar when in dark mode, Then how about changing the top bar color into white?

**Comment by dluvian** [comment]
Purple in light mode and black in dark mode is the default compose theme. The top bar uses `primary` color in light mode and `onSurface` in dark mode. I don't want to change the primary color, I quite like it.

**Comment by Yonle** [comment]
> Purple in light mode and black in dark mode is the default compose theme. The top bar uses `primary` color in light mode and `onSurface` in dark mode. I don't want to change the primary color, I quite like it.

It's a bit weird to see that they were using `primary` color as the top bar color.
