### ISSUE TITLE
bug: uncounted following

### ISSUE THREAD

**Issue by shortwavesurfer2009** [dluvian/Nozzle#66]
I have one account i am following but the screenshot below does not show it

![Screenshot_20240204-144132_Nozzle](https://github.com/dluvian/Nozzle/assets/116814522/16c81b97-be5c-459a-8ab2-bc89d2715aa4)

Howevee, if i tap "following" i get
![Screenshot_20240204-144332_Nozzle](https://github.com/dluvian/Nozzle/assets/116814522/390d9f69-ad58-4b70-aeca-f927b60fe11d)

**Comment by dluvian** [comment]
Thank you for reporting!
Fixed in 5adadbd5daad8529f90bd50368912f502f8fdede
It will be in the next release
