### ISSUE TITLE
[BUG] keyboard will not return

### ISSUE THREAD

**Issue by shortwavesurfer2009** [dluvian/Nozzle#72]
On the search page if you dismiss the keyboard the cursor continues to blink in the search field, but you cannot get the keyboard back without leaving the search page completely

https://github.com/dluvian/Nozzle/assets/116814522/0695a714-b169-4de4-8a41-e7ce2aef6a62

**Comment by dluvian** [comment]
I updated some dependencies in the latest release which solved this issue
