### ISSUE TITLE
possible incorrect follower counts?

### ISSUE THREAD

**Issue by shortwavesurfer2009** [dluvian/Nozzle#82]
Nozzle tells me i have 4 followers, but during a test of another client it said i have 10 followers. Any idea what may be causing the difference?

**Comment by dluvian** [comment]
Nozzle only counts the contact lists that are currently in the local database. Other clients might fetch a bunch of contact lists to check in how many you're in but Nozzle does not do this, so naturally the follower count is usually smaller than expected.
